CREATE DATABASE IF NOT EXISTS jiradb;
USE jiradb;
CREATE TABLE IF NOT EXISTS tasks (id INT PRIMARY KEY, title VARCHAR(100), description TEXT, status VARCHAR(10), priority VARCHAR(20), estimate_hours INT, depends_on INT NULL);
INSERT INTO tasks (id, title, description, status, priority, estimate_hours, depends_on) VALUES (1, 'Cập nhật biểu mẫu báo cáo', 'Mô tả chi tiết cho nhiệm vụ Cập nhật biểu mẫu báo cáo', 'TODO', 'Thấp', 2, NULL);
INSERT INTO tasks (id, title, description, status, priority, estimate_hours, depends_on) VALUES (2, 'Chuẩn hóa quy trình tiếp nhận yêu cầu', 'Mô tả chi tiết cho nhiệm vụ Chuẩn hóa quy trình tiếp nhận yêu cầu', 'DOING', 'Trung bình', 3, NULL);
INSERT INTO tasks (id, title, description, status, priority, estimate_hours, depends_on) VALUES (3, 'Thiết kế giao diện bảng Kanban', 'Mô tả chi tiết cho nhiệm vụ Thiết kế giao diện bảng Kanban', 'DONE', 'Cao', 4, NULL);
INSERT INTO tasks (id, title, description, status, priority, estimate_hours, depends_on) VALUES (4, 'Xây dựng API danh sách task', 'Mô tả chi tiết cho nhiệm vụ Xây dựng API danh sách task', 'TODO', 'Thấp', 5, 3);
INSERT INTO tasks (id, title, description, status, priority, estimate_hours, depends_on) VALUES (5, 'Đồng bộ hóa dữ liệu giữa client và server', 'Mô tả chi tiết cho nhiệm vụ Đồng bộ hóa dữ liệu giữa client và server', 'DOING', 'Trung bình', 2, NULL);
INSERT INTO tasks (id, title, description, status, priority, estimate_hours, depends_on) VALUES (6, 'Kiểm thử luồng tạo task mới', 'Mô tả chi tiết cho nhiệm vụ Kiểm thử luồng tạo task mới', 'DONE', 'Cao', 3, NULL);
INSERT INTO tasks (id, title, description, status, priority, estimate_hours, depends_on) VALUES (7, 'Triển khai tính năng kéo thả', 'Mô tả chi tiết cho nhiệm vụ Triển khai tính năng kéo thả', 'TODO', 'Thấp', 4, NULL);
INSERT INTO tasks (id, title, description, status, priority, estimate_hours, depends_on) VALUES (8, 'Tối ưu truy vấn BST theo ID', 'Mô tả chi tiết cho nhiệm vụ Tối ưu truy vấn BST theo ID', 'DOING', 'Trung bình', 5, 7);
INSERT INTO tasks (id, title, description, status, priority, estimate_hours, depends_on) VALUES (9, 'Viết unit test cho LinkedList', 'Mô tả chi tiết cho nhiệm vụ Viết unit test cho LinkedList', 'DONE', 'Cao', 2, NULL);
INSERT INTO tasks (id, title, description, status, priority, estimate_hours, depends_on) VALUES (10, 'Tích hợp cây phụ thuộc', 'Mô tả chi tiết cho nhiệm vụ Tích hợp cây phụ thuộc', 'TODO', 'Thấp', 3, NULL);
INSERT INTO tasks (id, title, description, status, priority, estimate_hours, depends_on) VALUES (11, 'Rà soát bảo mật API', 'Mô tả chi tiết cho nhiệm vụ Rà soát bảo mật API', 'DOING', 'Trung bình', 4, NULL);
INSERT INTO tasks (id, title, description, status, priority, estimate_hours, depends_on) VALUES (12, 'Chuẩn hóa logging Tomcat', 'Mô tả chi tiết cho nhiệm vụ Chuẩn hóa logging Tomcat', 'DONE', 'Cao', 5, 11);
INSERT INTO tasks (id, title, description, status, priority, estimate_hours, depends_on) VALUES (13, 'Cài đặt proxy Vite', 'Mô tả chi tiết cho nhiệm vụ Cài đặt proxy Vite', 'TODO', 'Thấp', 2, NULL);
INSERT INTO tasks (id, title, description, status, priority, estimate_hours, depends_on) VALUES (14, 'Chuẩn bị tài liệu README', 'Mô tả chi tiết cho nhiệm vụ Chuẩn bị tài liệu README', 'DOING', 'Trung bình', 3, NULL);
INSERT INTO tasks (id, title, description, status, priority, estimate_hours, depends_on) VALUES (15, 'Hội thảo demo với khách hàng', 'Mô tả chi tiết cho nhiệm vụ Hội thảo demo với khách hàng', 'DONE', 'Cao', 4, NULL);
INSERT INTO tasks (id, title, description, status, priority, estimate_hours, depends_on) VALUES (16, 'Hệ thống cảnh báo vòng lặp', 'Mô tả chi tiết cho nhiệm vụ Hệ thống cảnh báo vòng lặp', 'TODO', 'Thấp', 5, 15);
INSERT INTO tasks (id, title, description, status, priority, estimate_hours, depends_on) VALUES (17, 'Bổ sung trạng thái đếm thẻ', 'Mô tả chi tiết cho nhiệm vụ Bổ sung trạng thái đếm thẻ', 'DOING', 'Trung bình', 2, NULL);
INSERT INTO tasks (id, title, description, status, priority, estimate_hours, depends_on) VALUES (18, 'Làm sạch dữ liệu giả', 'Mô tả chi tiết cho nhiệm vụ Làm sạch dữ liệu giả', 'DONE', 'Cao', 3, NULL);
INSERT INTO tasks (id, title, description, status, priority, estimate_hours, depends_on) VALUES (19, 'Nâng cấp luồng move task', 'Mô tả chi tiết cho nhiệm vụ Nâng cấp luồng move task', 'TODO', 'Thấp', 4, NULL);
INSERT INTO tasks (id, title, description, status, priority, estimate_hours, depends_on) VALUES (20, 'Đánh giá trải nghiệm người dùng', 'Mô tả chi tiết cho nhiệm vụ Đánh giá trải nghiệm người dùng', 'DOING', 'Trung bình', 5, 19);
